<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AdaptiveSlop.Tests" />
  </ItemGroup>


  <ItemGroup>
    <Compile Include="Library.fs" />
    <Compile Include="Collections/Shared.fs" />
    <Compile Include="Collections/Changeable.fs" />
    <Compile Include="Collections/SetNodes.fs" />
    <Compile Include="Collections/MapNodes.fs" />
    <Compile Include="Collections/ObserveNodes.fs" />
    <Compile Include="Collections/ListNodes.fs" />
    <Compile Include="Collections/Reductions.fs" />
    <Compile Include="Collections/ElementSetNode.fs" />
    <Compile Include="Collections/ElementMapNode.fs" />
    <Compile Include="Collections/Api.fs" />
  </ItemGroup>

</Project>
